export const storeProducts = [
  {
    id: "1",
    name: "iPhone 11pro",
    image: "./images/11pro.jpg",
    price: 100,
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: "2",
    name: "phone",
    image: "./images/11pro.jpg",
    price: 100,
    count: 0,
    total: 0,
  },
  {
    id: "3",
    name: "iphone X",
    image: "./images/iphonex.jpg",
    price: 100,
    count: 0,
    total: 0,
  },
  {
    id: "4",
    name: "phone",
    image: "./images/iphone7plus.jpg",
    price: 100,
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: "5",
    name: "iPhone 11pro",
    image: "./images/11pro.jpg",
    price: 100,
    inCart: false,
    count: 0,
    total: 0,
  },
  { id: "6", name: "phone", image: "./images/11pro.jpg", price: 100 },
  {
    id: "7",
    name: "iphone X",
    image: "./images/iphonex.jpg",
    price: 100,
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: "8",
    name: "phone",
    image: "./images/iphone7plus.jpg",
    price: 100,
    inCart: false,
    count: 0,
    total: 0,
  },
];
