export const storeProducts = [
  {
    id: "1",
    name: "iPhone 11pro",
    image: "./images/11pro.jpg",
    price: 365000,
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: "2",
    name: "iPhone 6",
    image: "./images/iphone6.jpg",
    price: 65000,
    count: 0,
    total: 0,
  },
  {
    id: "3",
    name: "iPhone X",
    image: "./images/iphonex.jpg",
    price: 195000,
    count: 0,
    total: 0,
  },
  {
    id: "4",
    name: "iPhone 7 Plus",
    image: "./images/iphone7plus.jpg",
    price: 130000,
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: "5",
    name: "iPhone 7",
    image: "./images/iphone7.jpg",
    price: 90000,
    inCart: false,
    count: 0,
    total: 0,
  },
  { id: "6", name: "phone", image: "./images/11pro.jpg", price: 100 },
  {
    id: "7",
    name: "iPhone 12",
    image: "./images/iphone12.jpg",
    price: 560000,
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: "8",
    name: "iPhone 8 Plus",
    image: "./images/iphone8plus.jpg",
    price: 170000,
    inCart: false,
    count: 0,
    total: 0,
  },
];
